#!/usr/bin/perl -w

use strict;

my ($WORKSPACE, $SCHEME, $ACTION) = @ARGV;

my $buildSettings = qx{xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -showBuildSettings};

my @args = ("-workspace", $WORKSPACE, "-scheme", $SCHEME, split(/\s+/, $ACTION), "CODE_SIGNING_REQUIRED=NO", "CODE_SIGN_IDENTITY=");

if ($buildSettings =~ /\bPLATFORM_NAME = iphoneos/i) {
  unshift @args, "-destination", "id=31E6604A-19AA-4B68-B560-C33C584BC80D"; # iPhone 6s, iOS 10.2
  unshift @args, "-sdk", "iphonesimulator";
}

print "xcodebuild @args\n";
exec("xcodebuild", @args);
