//
//  UIColor+MMRAdditions.swift
//
//  Generated by Zeplin on 4/1/17.
//  Copyright (c) 2017 __MyCompanyName__. All rights reserved. 
//

import UIKit

extension UIColor {
	class var mmrBlack: UIColor { 
		return UIColor(white: 51.0 / 255.0, alpha: 1.0)
	}

	class var mmrSunflowerYellow: UIColor {
		return UIColor(red: 255.0 / 255.0, green: 205.0 / 255.0, blue: 0.0, alpha: 1.0)
	}

	class var mmrWhite: UIColor { 
		return UIColor(white: 221.0 / 255.0, alpha: 1.0)
	}

	class var mmrGreyishBrown: UIColor { 
		return UIColor(white: 68.0 / 255.0, alpha: 1.0)
	}

	class var mmrSunflowerYellow90: UIColor {
		return UIColor(red: 255.0 / 255.0, green: 204.0 / 255.0, blue: 0.0, alpha: 0.9)
	}

	class var mmrRed: UIColor {
		return UIColor(red: 204.0 / 255.0, green: 0.0, blue: 0.0, alpha: 1.0)
	}
}
