//
//  UIFont+MMRAdditions.swift
//
//  Generated by Zeplin on 4/1/17.
//  Copyright (c) 2017 __MyCompanyName__. All rights reserved. 
//

import UIKit

extension UIFont {
	class func mmrPlaceholderFont() -> UIFont {
		return UIFont.systemFont(ofSize: 36.0, weight: UIFontWeightSemibold)
	}

	class func mmrHomeCategoryFont() -> UIFont {
		return UIFont.systemFont(ofSize: 17.0, weight: UIFontWeightSemibold)
	}

	class func mmrPostTitleFont() -> UIFont {
		return UIFont.systemFont(ofSize: 17.0, weight: UIFontWeightLight)
	}
}
